accounts:
  - name: alice
    coins: ["20000token", "200000000stake"]
  - name: bob
    coins: ["10000token", "100000000stake"]
validator:
  name: alice
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
  host: ":4501"
host:
  rpc: ":26661"
  p2p: ":26660"
  prof: ":6062"
  grpc: ":9092"
  grpc-web: "0.0.0.0:9093"
  api: ":1319"